export type Mode = 'discovery' | 'therapeutics' | 'conditioning';
export type NeurologicalProfile = 'neurotypical' | 'adhd' | 'asd';
export type AgeCohort = 'youth' | 'adult' | 'elderly';
export type Modality = 'audio' | 'text' | 'image';
export type StimulusType = 'text' | 'image' | 'video' | 'audio';
export type InferenceMode = 'mock' | 'tribe' | 'unknown';
export type GenerationMode = 'simulation' | 'model_loop' | 'unknown';
export type BackendReachability = 'checking' | 'online' | 'offline';

export type BackendHealthResponse = {
  status?: string;
  queue_backend?: string;
  inference_mode?: string;
  generate_mode?: string;
  generate_model_loop_validated?: boolean;
  generate_model_loop_validation_report_configured?: boolean;
  generate_model_loop_validation_report?: string;
  generate_model_loop_signed_off?: boolean;
  generate_model_loop_signoff_report_configured?: boolean;
  generate_model_loop_signoff_report?: string;
  generate_model_loop_iterations?: number;
  metrics_enabled?: boolean;
  metrics_require_api_key?: boolean;
  otel_enabled?: boolean;
  otel_service_name?: string;
  tribe_model_status?: string;
  tribe_checkpoint_configured?: boolean;
  max_upload_mb?: number;
  upload_ttl_hours?: number;
  upload_cleanup_interval_seconds?: number;
  delete_uploads_after_inference?: boolean;
  api_key_required?: boolean;
  rate_limit_enabled?: boolean;
  rate_limit_window_seconds?: number;
  rate_limit_max_requests?: number;
  async_job_queue_enabled?: boolean;
  job_worker_concurrency?: number;
  job_queue_max_pending?: number;
  job_queue_depth?: number;
};
